# Generated by Django 4.1.5 on 2023-05-30 23:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("deducciones", "0002_alter_deduccionempleado_validity_from_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deduccion",
            name="validity_from",
            field=models.DateField(
                default=datetime.datetime(2000, 1, 1, 0, 0),
                verbose_name="Vigencia desde",
            ),
        ),
        migrations.AlterField(
            model_name="deduccion",
            name="validity_to",
            field=models.DateField(
                default=datetime.datetime(2500, 12, 31, 0, 0),
                verbose_name="Vigencia hasta",
            ),
        ),
        migrations.AlterField(
            model_name="deduccionempleado",
            name="validity_from",
            field=models.DateField(
                blank=True, null=True, verbose_name="Vigencia desde"
            ),
        ),
        migrations.AlterField(
            model_name="deduccionempleado",
            name="validity_to",
            field=models.DateField(
                blank=True, null=True, verbose_name="Vigencia hasta"
            ),
        ),
    ]
