# Generated by Django 4.1.5 on 2023-05-25 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ganancias.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Concepto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Tipo Concepto",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Deduccion",
            fields=[
                (
                    "codigo_siradig",
                    models.PositiveSmallIntegerField(
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Código Siradig",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Nombre")),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("DG", "Deducción General"),
                            ("DP", "Deducción Personal"),
                        ],
                        default="DG",
                        max_length=2,
                    ),
                ),
                (
                    "periodicidad",
                    models.CharField(
                        choices=[("AN", "Anual"), ("ME", "Mensual")],
                        default="ME",
                        max_length=2,
                    ),
                ),
                (
                    "tope",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Sin Tope"),
                            (1, "Tope 5% Ganan 1"),
                            (2, "Tope 5% Ganan 2"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "informa_en_unidad",
                    models.BooleanField(
                        default=False, verbose_name="¿Informa en unidad?"
                    ),
                ),
                (
                    "es_pago_ac",
                    models.BooleanField(
                        default=False, verbose_name="¿Es pago a cuenta?"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Deducciones",
            },
        ),
        migrations.CreateModel(
            name="TipoConcepto",
            fields=[
                (
                    "code",
                    models.CharField(
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Código Tipo",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Tipo Concepto",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Liquidacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("periodo", models.DateField()),
                ("payday", models.DateField()),
            ],
            options={
                "verbose_name_plural": "Liquidaciones",
                "ordering": ["payday"],
                "unique_together": {("periodo", "payday")},
            },
        ),
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=120,
                        validators=[ganancias.validators.validate_name],
                        verbose_name="Razon Social",
                    ),
                ),
                (
                    "cuit",
                    models.CharField(
                        max_length=11, validators=[ganancias.validators.validate_cuit]
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Empleado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("leg", models.IntegerField()),
                (
                    "name",
                    models.CharField(
                        max_length=120,
                        validators=[ganancias.validators.validate_name],
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "cuil",
                    models.CharField(
                        max_length=11, validators=[ganancias.validators.validate_cuil]
                    ),
                ),
                (
                    "area",
                    models.CharField(
                        blank=True,
                        max_length=120,
                        null=True,
                        verbose_name="Área de Trabajo",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ganancias.empresa",
                    ),
                ),
            ],
            options={
                "ordering": ["empresa__name", "leg"],
                "unique_together": {("leg", "empresa")},
            },
        ),
        migrations.CreateModel(
            name="ConceptoLiquidado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("importe", models.FloatField(default=0.0)),
                (
                    "concepto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ganancias.concepto",
                    ),
                ),
                (
                    "empleado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ganancias.empleado",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="concepto",
            name="tipo_concepto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ganancias.tipoconcepto"
            ),
        ),
    ]
