# Generated by Django 4.1.5 on 2023-01-21 15:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concepto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo Concepto')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True, verbose_name='Nombre')),
                ('cuil', models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(11)])),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TipoConcepto',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='Código Tipo')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo Concepto')),
            ],
        ),
        migrations.CreateModel(
            name='Liquidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.DateField()),
                ('payday', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Liquidaciones',
                'ordering': ['payday'],
                'unique_together': {('periodo', 'payday')},
            },
        ),
        migrations.CreateModel(
            name='ConceptoLiquidado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importe', models.FloatField(default=0.0)),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ganancias.concepto')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ganancias.empleado')),
            ],
        ),
        migrations.AddField(
            model_name='concepto',
            name='tipo_concepto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ganancias.tipoconcepto'),
        ),
    ]
