# Generated by Django 4.1.5 on 2023-05-25 12:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ganancias", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="deduccion",
            options={
                "ordering": ["tipo", "codigo_siradig"],
                "verbose_name_plural": "Deducciones",
            },
        ),
    ]
