# Generated by Django 4.1.5 on 2023-05-25 23:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ganancias", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="concepto",
            name="name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Nombre"
            ),
        ),
    ]
