# Generated by Django 4.1.5 on 2023-01-21 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ganancias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deduccion',
            fields=[
                ('codigo_siradig', models.PositiveSmallIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Código Siradig')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre')),
                ('tipo', models.CharField(choices=[('DG', 'Deducción General'), ('DP', 'Deducción Personal')], default='DG', max_length=2)),
                ('periodicidad', models.CharField(choices=[('AN', 'Anual'), ('ME', 'Mensual')], default='ME', max_length=2)),
                ('tope', models.PositiveSmallIntegerField(choices=[(0, 'Sin Tope'), (1, 'Tope 5\\% Ganan 1'), (2, 'Tope 5\\% Ganan 2')], default=0)),
                ('ccn_sueldo', models.CharField(max_length=20, verbose_name='Código de Concepto Sueldo')),
                ('es_pago_ac', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Deducciones',
            },
        ),
    ]
