# Generated by Django 4.1.5 on 2023-05-29 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ganancias", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeduccionEmpleado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period", models.DateField(verbose_name="Periodo")),
                ("value", models.FloatField(default=0.0, verbose_name="Importe")),
                (
                    "deduccion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ganancias.deduccion",
                    ),
                ),
                (
                    "empleado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ganancias.empleado",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Deducciones Empleado",
                "ordering": ["empleado", "deduccion"],
            },
        ),
    ]
