# Generated by Django 4.1.5 on 2023-05-29 20:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ganancias", "0002_deduccionempleado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empresa",
            name="take_sac",
            field=models.CharField(
                choices=[("AN", "Anual"), ("ME", "Mensual")],
                default="AN",
                max_length=2,
                verbose_name="Consideración SAC",
            ),
        ),
    ]
