# Generated by Django 4.1.5 on 2023-01-21 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ganancias', '0002_deduccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deduccion',
            name='ccn_sueldo',
        ),
        migrations.AlterField(
            model_name='deduccion',
            name='es_pago_ac',
            field=models.BooleanField(default=False, verbose_name='¿Es pago a cuenta?'),
        ),
    ]
