# Generated by Django 4.1.5 on 2023-05-26 20:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ganancias", "0002_alter_concepto_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="TablaArt94",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period", models.DateField()),
                ("from_value", models.FloatField(default=0.0)),
                ("to_value", models.FloatField(default=0.0)),
                ("tax_percent", models.FloatField(default=0.0)),
                ("tax_fixed", models.FloatField(default=0.0)),
            ],
        ),
        migrations.AlterModelOptions(
            name="concepto",
            options={"ordering": ["others", "exento", "tipo_concepto", "name"]},
        ),
    ]
