# Generated by Django 4.1.5 on 2023-05-29 21:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("ganancias", "0003_alter_empresa_take_sac"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deduccionempleado",
            name="period",
        ),
        migrations.AddField(
            model_name="deduccionempleado",
            name="nombre",
            field=models.CharField(
                blank=True,
                max_length=120,
                null=True,
                verbose_name="Nombre - Razón Social",
            ),
        ),
        migrations.AddField(
            model_name="deduccionempleado",
            name="validity_from",
            field=models.DateField(
                blank=True,
                default=django.utils.timezone.now,
                verbose_name="Vigencia desde",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="deduccionempleado",
            name="validity_to",
            field=models.DateField(
                blank=True,
                default=django.utils.timezone.now,
                verbose_name="Vigencia hasta",
            ),
            preserve_default=False,
        ),
    ]
