# Generated by Django 4.1.5 on 2023-05-26 23:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "ganancias",
            "0004_alter_tablaart94_options_alter_tablaart94_from_value_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="topevalor",
            old_name="periodo",
            new_name="period",
        ),
        migrations.RenameField(
            model_name="topevalor",
            old_name="valor",
            new_name="value",
        ),
    ]
