# Generated by Django 4.1.5 on 2023-05-26 23:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ganancias", "0005_rename_periodo_topevalor_period_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="topevalor",
            options={"ordering": ["-period", "tope"]},
        ),
        migrations.AlterUniqueTogether(
            name="topevalor",
            unique_together={("tope", "period")},
        ),
    ]
