# Generated by Django 4.1.5 on 2023-05-27 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ganancias", "0006_alter_topevalor_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PeriodoDeduccionIncrementada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "validity_from",
                    models.DateField(
                        blank=True, null=True, verbose_name="Vigencia desde"
                    ),
                ),
                (
                    "validity_to",
                    models.DateField(
                        blank=True, null=True, verbose_name="Vigencia hasta"
                    ),
                ),
                (
                    "sac_exento_limit",
                    models.FloatField(default=0.0, verbose_name="Importe"),
                ),
            ],
            options={
                "verbose_name_plural": "Periodo Deducción Incrementada",
                "ordering": ["-validity_from"],
            },
        ),
        migrations.RenameField(
            model_name="liquidacion",
            old_name="periodo",
            new_name="period",
        ),
        migrations.AlterUniqueTogether(
            name="liquidacion",
            unique_together={("period", "payday")},
        ),
        migrations.CreateModel(
            name="DeduccionIncrementadaDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_value", models.FloatField(default=0.0, verbose_name="Desde")),
                ("to_value", models.FloatField(default=0.0, verbose_name="Hasta")),
                ("value", models.FloatField(default=0.0, verbose_name="Importe")),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ganancias.periododeduccionincrementada",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Detalle Deducción Incrementada",
                "ordering": ["-period", "value"],
            },
        ),
    ]
