# Generated by Django 4.1.5 on 2023-05-27 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ganancias", "0008_alter_topevalor_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="deduccionincrementadadetail",
            options={
                "ordering": ["period", "value"],
                "verbose_name_plural": "Detalle Deducción Incrementada",
            },
        ),
        migrations.AlterField(
            model_name="deduccionincrementadadetail",
            name="period",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="ganancias.periododeduccionincrementada",
                verbose_name="Periodo",
            ),
        ),
    ]
