# Generated by Django 4.1.5 on 2023-05-27 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ganancias", "0009_alter_deduccionincrementadadetail_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OtrosConceptos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "concepto",
                    models.CharField(
                        choices=[("SICOSS", "Tope SICOSS"), ("EXBO", "Exención Bono")],
                        max_length=10,
                    ),
                ),
                (
                    "validity_from",
                    models.DateField(
                        blank=True, null=True, verbose_name="Vigencia desde"
                    ),
                ),
                (
                    "validity_to",
                    models.DateField(
                        blank=True, null=True, verbose_name="Vigencia hasta"
                    ),
                ),
                ("value", models.FloatField(default=0.0, verbose_name="Importe")),
            ],
        ),
    ]
