# Generated by Django 4.1.5 on 2023-05-27 13:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ganancias", "0010_otrosconceptos"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="otrosconceptos",
            options={
                "ordering": ["concepto"],
                "verbose_name_plural": "Otros Conceptos",
            },
        ),
    ]
