# Generated by Django 4.1.5 on 2023-06-06 16:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("f1357", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="f1357field",
            old_name="descripcion",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="group",
            old_name="descripcion",
            new_name="description",
        ),
    ]
