# Generated by Django 4.1.5 on 2023-06-06 23:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import empresa.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=120,
                        validators=[empresa.validators.validate_name],
                        verbose_name="Razon Social",
                    ),
                ),
                (
                    "cuit",
                    models.CharField(
                        max_length=11, validators=[empresa.validators.validate_cuit]
                    ),
                ),
                (
                    "take_sac",
                    models.CharField(
                        choices=[("AN", "Anual"), ("JD", "Junio - Diciembre")],
                        default="AN",
                        max_length=2,
                        verbose_name="Consideración SAC",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Empleado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("leg", models.IntegerField()),
                (
                    "name",
                    models.CharField(
                        max_length=120,
                        validators=[empresa.validators.validate_name],
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "cuil",
                    models.CharField(
                        max_length=11, validators=[empresa.validators.validate_cuil]
                    ),
                ),
                ("jubilado", models.BooleanField(default=False)),
                (
                    "zona_patagonica",
                    models.BooleanField(default=False, verbose_name="Zona Patagónica"),
                ),
                (
                    "fecha_baja",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Baja"
                    ),
                ),
                (
                    "tope_35_anual",
                    models.BooleanField(
                        default=True, verbose_name="Tope Límite 35% Liq. Anual"
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="empresa.empresa",
                    ),
                ),
            ],
            options={
                "ordering": ["empresa__name", "leg"],
                "unique_together": {("leg", "empresa")},
            },
        ),
    ]
