name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8, "3.10"]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint with Flake8
      run: |
        flake8 \
        --count \
        --show-source \
        --max-complexity=10 \
        --max-line-length=130 \
        --statistics \
        --ignore=C901,F811 \
        --exclude=migrations

    - name: Check pending migrations
      run: |
        python manage.py makemigrations --check --dry-run
        python manage.py migrate

    - name: Run Tests
      run: |
        python manage.py test

    - name: Test commands to init DB 
      run: |
        python manage.py init_deducciones
        python manage.py init_conceptos
        python manage.py init_tablas
